---
- name: Query Cloudflare API for existing Origin Certificates
  ansible.builtin.uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ cf_zone_id }}/origin_tls_client_auth"
    method: GET
    headers:
      Authorization: "Bearer {{ cf_api_token }}"
      Content-Type: "application/json"
    return_content: true
    status_code: [200]
  register: existing_certs_response
  failed_when: >
    existing_certs_response.status != 200 or
    (existing_certs_response.json is defined and existing_certs_response.json.get('success') == false)
  ignore_errors: true

- name: Handle API call failure for listing certificates
  ansible.builtin.set_fact:
    api_call_failed: true
  when: >
    existing_certs_response.failed or
    (existing_certs_response.status != 200) or
    (existing_certs_response.json is not defined or not existing_certs_response.json.get('success'))
- name: Inform about API call failure if it occurred
  ansible.builtin.fail:
    msg: >
      Failed to retrieve existing certificates from Cloudflare.
      Status: {{ existing_certs_response.status | default('N/A') }}
      Reason: {{
        'URI task itself failed or conditions unmet.' if existing_certs_response.failed
        else 'API reported non-success or unexpected structure.'
      }}
      Response: {{ existing_certs_response.content | default(existing_certs_response.msg) | default('N/A') }}
  when: api_call_failed | default(false)
