---
- name: Download and install Cloudflare Origin CA RSA root certificate
  ansible.builtin.get_url:
    url: "https://developers.cloudflare.com/ssl/static/origin_ca_rsa_root.pem"
    dest: "{{ cf_certificate_install_path }}cloudflare_origin_rsa_root.pem"
    mode: '0644'
    force: false
