---
name: Ansible Role CI - Cloudflare Origin Cert

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint Ansible Role
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python for Ansible
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and ansible-lint
        run: pip install ansible ansible-lint yamllint

      - name: Set up Ansible roles path for testing
        run: |
          mkdir -p "${{ github.workspace }}/.ansible_test_roles"
          ln -s "${{ github.workspace }}" "${{ github.workspace }}/.ansible_test_roles/cloudflare_origin_cert"
          echo "ANSIBLE_ROLES_PATH=${{ github.workspace }}/.ansible_test_roles" >> $GITHUB_ENV

      - name: Run yamllint
        run: yamllint .

      - name: Run ansible-lint
        run: ansible-lint -v

  integration_test:
    name: Test Cloudflare Origin Cert Role
    runs-on: ubuntu-latest
    needs: lint
    env:
      CF_API_TOKEN_SECRET: ${{ secrets.CF_API_TOKEN }}
      CF_ZONE_ID_SECRET: ${{ secrets.CF_ZONE_ID }}
      CF_CERTIFICATE_HOSTNAMES_VAR: ${{ vars.CF_CERTIFICATE_HOSTNAMES_TEST }}

      # Ansible configuration
      ANSIBLE_FORCE_COLOR: "1"
      ANSIBLE_HOST_KEY_CHECKING: "False"
      ANSIBLE_NOCOWS: "1"
      PY_COLORS: "1"

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python for Ansible
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible requests

      - name: Set up Ansible roles path for testing
        run: |
          mkdir -p "${{ github.workspace }}/.ansible_test_roles"
          ln -s "${{ github.workspace }}" "${{ github.workspace }}/.ansible_test_roles/cloudflare_origin_cert"
          echo "ANSIBLE_ROLES_PATH=${{ github.workspace }}/.ansible_test_roles" >> $GITHUB_ENV

      - name: Run Ansible playbook for testing the role
        run: ansible-playbook tests/test-role.yml -i tests/inventory.ini --verbose
